(function(g){function k(){}function v(a,b){return function(){a.apply(b,arguments)}}function p(a){if("object"!==typeof this)throw new TypeError("Promises must be constructed via new");if("function"!==typeof a)throw new TypeError("not a function");this._state=0;this._handled=!1;this._value=void 0;this._deferreds=[];d(a,this)}function y(a,c){for(;3===a._state;)a=a._value;0===a._state?a._deferreds.push(c):(a._handled=!0,p._immediateFn(function(){var f=1===a._state?c.onFulfilled:c.onRejected;if(null===
f)(1===a._state?q:b)(c.promise,a._value);else{try{var d=f(a._value)}catch(n){b(c.promise,n);return}q(c.promise,d)}}))}function q(c,e){try{if(e===c)throw new TypeError("A promise cannot be resolved with itself.");if(e&&("object"===typeof e||"function"===typeof e)){var f=e.then;if(e instanceof p){c._state=3;c._value=e;a(c);return}if("function"===typeof f){d(v(f,e),c);return}}c._state=1;c._value=e;a(c)}catch(C){b(c,C)}}function b(b,c){b._state=2;b._value=c;a(b)}function a(a){2===a._state&&0===a._deferreds.length&&
p._immediateFn(function(){a._handled||p._unhandledRejectionFn(a._value)});for(var b=0,c=a._deferreds.length;b<c;b++)y(a,a._deferreds[b]);a._deferreds=null}function c(a,b,c){this.onFulfilled="function"===typeof a?a:null;this.onRejected="function"===typeof b?b:null;this.promise=c}function d(a,c){var e=!1;try{a(function(a){e||(e=!0,q(c,a))},function(a){e||(e=!0,b(c,a))})}catch(C){e||(e=!0,b(c,C))}}if(!g.Promise){var e=setTimeout;p.prototype["catch"]=function(a){return this.then(null,a)};p.prototype.then=
function(a,b){var e=new this.constructor(k);y(this,new c(a,b,e));return e};p.all=function(a){var b=Array.prototype.slice.call(a);return new p(function(a,c){function e(h,f){try{if(f&&("object"===typeof f||"function"===typeof f)){var g=f.then;if("function"===typeof g){g.call(f,function(a){e(h,a)},c);return}}b[h]=f;0===--d&&a(b)}catch(D){c(D)}}if(0===b.length)return a([]);for(var d=b.length,f=0;f<b.length;f++)e(f,b[f])})};p.resolve=function(a){return a&&"object"===typeof a&&a.constructor===p?a:new p(function(b){b(a)})};
p.reject=function(a){return new p(function(b,c){c(a)})};p.race=function(a){return new p(function(b,c){for(var e=0,d=a.length;e<d;e++)a[e].then(b,c)})};p._immediateFn="function"===typeof setImmediate&&function(a){setImmediate(a)}||function(a){e(a,0)};p._unhandledRejectionFn=function(a){"undefined"!==typeof console&&console&&console.warn("Possible Unhandled Promise Rejection:",a)};p._setImmediateFn=function(a){p._immediateFn=a};p._setUnhandledRejectionFn=function(a){p._unhandledRejectionFn=a};g.Promise=
p}})(this);
(function(g,k){g.ResizeObserver=k()})(this,function(){function g(a){for(var b=[],c=arguments.length-1;0<c--;)b[c]=arguments[c+1];return b.reduce(function(b,c){return b+(parseFloat(a["border-"+c+"-width"])||0)},0)}var k=function(){function a(a,b){var c=-1;a.some(function(a,h){return a[0]===b?(c=h,!0):!1});return c}return"undefined"!==typeof Map?Map:function(){function b(){this.__entries__=[]}var c={size:{configurable:!0}};c.size.get=function(){return this.__entries__.length};b.prototype.get=function(b){b=
a(this.__entries__,b);return(b=this.__entries__[b])&&b[1]};b.prototype.set=function(b,c){var h=a(this.__entries__,b);~h?this.__entries__[h][1]=c:this.__entries__.push([b,c])};b.prototype["delete"]=function(b){var c=this.__entries__;b=a(c,b);~b&&c.splice(b,1)};b.prototype.has=function(b){return!!~a(this.__entries__,b)};b.prototype.clear=function(){this.__entries__.splice(0)};b.prototype.forEach=function(a,b){void 0===b&&(b=null);for(var c=0,h=this.__entries__;c<h.length;c+=1){var e=h[c];a.call(b,e[1],
e[0])}};Object.defineProperties(b.prototype,c);return b}()}(),v="undefined"!==typeof window&&"undefined"!==typeof document&&window.document===document,p="undefined"!==typeof global&&global.Math===Math?global:"undefined"!==typeof self&&self.Math===Math?self:"undefined"!==typeof window&&Math===Math?window:Function("return this")(),y=function(){return"function"===typeof requestAnimationFrame?requestAnimationFrame.bind(p):function(a){return setTimeout(function(){return a(Date.now())},1E3/60)}}(),q=function(a,
b){function c(){d&&(d=!1,a());f&&e()}function h(){y(c)}function e(){var a=Date.now();if(d){if(2>a-g)return;f=!0}else d=!0,f=!1,setTimeout(h,b);g=a}var d=!1,f=!1,g=0;return e},b="top right bottom left width height size weight".split(" "),a="undefined"!==typeof MutationObserver,c=function(){this.mutationEventsAdded_=this.connected_=!1;this.mutationsObserver_=null;this.observers_=[];this.onTransitionEnd_=this.onTransitionEnd_.bind(this);this.refresh=q(this.refresh.bind(this),20)};c.prototype.addObserver=
function(a){~this.observers_.indexOf(a)||this.observers_.push(a);this.connected_||this.connect_()};c.prototype.removeObserver=function(a){var b=this.observers_;a=b.indexOf(a);~a&&b.splice(a,1);!b.length&&this.connected_&&this.disconnect_()};c.prototype.refresh=function(){this.updateObservers_()&&this.refresh()};c.prototype.updateObservers_=function(){var a=this.observers_.filter(function(a){return a.gatherActive(),a.hasActive()});a.forEach(function(a){return a.broadcastActive()});return 0<a.length};
c.prototype.connect_=function(){v&&!this.connected_&&(document.addEventListener("transitionend",this.onTransitionEnd_),window.addEventListener("resize",this.refresh),a?(this.mutationsObserver_=new MutationObserver(this.refresh),this.mutationsObserver_.observe(document,{attributes:!0,childList:!0,characterData:!0,subtree:!0})):(document.addEventListener("DOMSubtreeModified",this.refresh),this.mutationEventsAdded_=!0),this.connected_=!0)};c.prototype.disconnect_=function(){v&&this.connected_&&(document.removeEventListener("transitionend",
this.onTransitionEnd_),window.removeEventListener("resize",this.refresh),this.mutationsObserver_&&this.mutationsObserver_.disconnect(),this.mutationEventsAdded_&&document.removeEventListener("DOMSubtreeModified",this.refresh),this.mutationsObserver_=null,this.connected_=this.mutationEventsAdded_=!1)};c.prototype.onTransitionEnd_=function(a){var c=a.propertyName;void 0===c&&(c="");b.some(function(a){return!!~c.indexOf(a)})&&this.refresh()};c.getInstance=function(){this.instance_||(this.instance_=new c);
return this.instance_};c.instance_=null;var d=function(a,b){for(var c=0,h=Object.keys(b);c<h.length;c+=1){var e=h[c];Object.defineProperty(a,e,{value:b[e],enumerable:!1,writable:!1,configurable:!0})}return a},e=function(a){return a&&a.ownerDocument&&a.ownerDocument.defaultView||p},m={x:0,y:0,width:0,height:0},u=function(){return"undefined"!==typeof SVGGraphicsElement?function(a){return a instanceof e(a).SVGGraphicsElement}:function(a){return a instanceof e(a).SVGElement&&"function"===typeof a.getBBox}}(),
f=function(a){this.broadcastHeight=this.broadcastWidth=0;this.contentRect_={x:0,y:0,width:0,height:0};this.target=a};f.prototype.isActive=function(){var a=this.target;if(v)if(u(a)){var b=a.getBBox();b={x:0,y:0,width:b.width,height:b.height}}else{var c=a.clientWidth,d=a.clientHeight;if(c||d){var f=e(a).getComputedStyle(a);b={};for(var r=0,n=["top","right","bottom","left"];r<n.length;r+=1){var k=n[r];b[k]=parseFloat(f["padding-"+k])||0}var t=b.left+b.right;k=b.top+b.bottom;r=parseFloat(f.width)||0;
n=parseFloat(f.height)||0;"border-box"===f.boxSizing&&(Math.round(r+t)!==c&&(r-=g(f,"left","right")+t),Math.round(n+k)!==d&&(n-=g(f,"top","bottom")+k));a!==e(a).document.documentElement&&(a=Math.round(r+t)-c,d=Math.round(n+k)-d,1!==Math.abs(a)&&(r-=a),1!==Math.abs(d)&&(n-=d));b={x:b.left,y:b.top,width:r,height:n}}else b=m}else b=m;this.contentRect_=b;return b.width!==this.broadcastWidth||b.height!==this.broadcastHeight};f.prototype.broadcastRect=function(){var a=this.contentRect_;this.broadcastWidth=
a.width;this.broadcastHeight=a.height;return a};var C=function(a,b){var c=b.x,h=b.y,e=b.width;b=b.height;var f=Object.create(("undefined"!==typeof DOMRectReadOnly?DOMRectReadOnly:Object).prototype);d(f,{x:c,y:h,width:e,height:b,top:h,right:c+e,bottom:b+h,left:c});d(this,{target:a,contentRect:f})},n=function(a,b,c){this.activeObservations_=[];this.observations_=new k;if("function"!==typeof a)throw new TypeError("The callback provided as parameter 1 is not a function.");this.callback_=a;this.controller_=
b;this.callbackCtx_=c};n.prototype.observe=function(a){if(!arguments.length)throw new TypeError("1 argument required, but only 0 present.");if("undefined"!==typeof Element&&Element instanceof Object){if(!(a instanceof e(a).Element))throw new TypeError('parameter 1 is not of type "Element".');var b=this.observations_;b.has(a)||(b.set(a,new f(a)),this.controller_.addObserver(this),this.controller_.refresh())}};n.prototype.unobserve=function(a){if(!arguments.length)throw new TypeError("1 argument required, but only 0 present.");
if("undefined"!==typeof Element&&Element instanceof Object){if(!(a instanceof e(a).Element))throw new TypeError('parameter 1 is not of type "Element".');var b=this.observations_;b.has(a)&&(b["delete"](a),b.size||this.controller_.removeObserver(this))}};n.prototype.disconnect=function(){this.clearActive();this.observations_.clear();this.controller_.removeObserver(this)};n.prototype.gatherActive=function(){var a=this;this.clearActive();this.observations_.forEach(function(b){b.isActive()&&a.activeObservations_.push(b)})};
n.prototype.broadcastActive=function(){if(this.hasActive()){var a=this.callbackCtx_,b=this.activeObservations_.map(function(a){return new C(a.target,a.broadcastRect())});this.callback_.call(a,b,a);this.clearActive()}};n.prototype.clearActive=function(){this.activeObservations_.splice(0)};n.prototype.hasActive=function(){return 0<this.activeObservations_.length};var t="undefined"!==typeof WeakMap?new WeakMap:new k,r=function(a){if(!(this instanceof r))throw new TypeError("Cannot call a class as a function.");
if(!arguments.length)throw new TypeError("1 argument required, but only 0 present.");var b=c.getInstance();b=new n(a,b,this);t.set(this,b)};["observe","unobserve","disconnect"].forEach(function(a){r.prototype[a]=function(){return(b=t.get(this))[a].apply(b,arguments);var b}});return"undefined"!==typeof p.ResizeObserver?p.ResizeObserver:p.ResizeObserver=r});
document.getElementsByClassName||(document.getElementsByClassName=function(g){return querySelectorAll("."+g)},Element.prototype.getElementsByClassName=document.getElementsByClassName);
!window.addEventListener&&function(g,k,v,p,y,q,b){g[p]=k[p]=v[p]=function(a,c){var d=this;b.unshift([d,a,c,function(a){a.currentTarget=d;a.preventDefault=function(){a.returnValue=!1};a.stopPropagation=function(){a.cancelBubble=!0};a.target=a.srcElement||d;c.call(d,a)}]);this.attachEvent("on"+a,b[0][3])};g[y]=k[y]=v[y]=function(a,c){for(var d=0,e;e=b[d];++d)if(e[0]==this&&e[1]==a&&e[2]==c)return this.detachEvent("on"+a,b.splice(d,1)[0][3])};g[q]=k[q]=v[q]=function(a){return this.fireEvent("on"+a.type,
a)}}(Window.prototype,HTMLDocument.prototype,Element.prototype,"addEventListener","removeEventListener","dispatchEvent",[]);NodeList.forEach||(NodeList.prototype.forEach=Array.prototype.forEach);Object.values||(Object.values=function(g){var k=[],v;for(v in g)g.hasOwnProperty(v)&&k.push(g[v]);return k});
"function"!=typeof CustomEvent&&(CustomEvent=function(g,k){k=k||{bubbles:!1,cancelable:!1,detail:null};var v=document.createEvent("CustomEvent");v.initCustomEvent(g,!!k.bubbles,!!k.cancelable,"undefined"==typeof k.detail?null:k.detail);return v});var NativendoNlpFeature=!0;
try{URL.prototype.normalize=function(){try{if(!/^https?:\/\/[^\/]/i.test(this.href))throw"Invalid URL";this.hash=this.password=this.username="";try{this.pathname=decodeURI(this.pathname)}catch(v){}this.hostname=this.hostname.replace(/\.$/,"");/^www\.(?:[a-z\-\d]{2,63})\.(?:[a-z.]{2,5})$/i.test(this.hostname)&&(this.hostname=this.hostname.replace(/^www\./i,""));this.pathname=this.pathname.replace(/\/\/+/g,"/");var g=[{pattern:"^utm_",flags:"i"},{pattern:"^pk_campaign$",flags:"i"},{pattern:"^pk_source$",
flags:"i"},{pattern:"^pk_medium$",flags:"i"},{pattern:"^pk_keyword$",flags:"i"},{pattern:"^pk_content$",flags:"i"},{pattern:"^pk_cid$",flags:"i"}],k=[];this.searchParams.forEach(function(v,p){g.every(function(g){return(new RegExp(g.pattern,g.flags)).test(p)?(k.push(p),!1):!0})});k.forEach(function(g){this.searchParams.delete(g)},this);this.searchParams.sort();return this.toString().replace(/^https?:\/\//i,"//").replace(/\/(\?.*?)?$/,"$1")}catch(v){NativendoNlpFeature=!1}return!1}}catch(g){NativendoNlpFeature=
!1}String.prototype.toKeywords=function(){for(var g=this.toLowerCase().replace(/[\r\n\t\u00a0\u2009]+/g," ").replace(/[.,\/\\#!$\u20ac%\^\u00b0&\*;:\{\}=_`~()\?"'\u2018-\u201f]/g,"").replace(/\s{2,}/g," ").trim().split(" "),k=[],v=0,p=g.length;v<p;v++)-1===k.indexOf(g[v])&&k.push(g[v]);return k.filter(function(g){return!(g.match(/^\d+$/g)||2>=g.length)}).sort()};var dummy=function(){};["log","debug","info","warn","error"].forEach(function(g){window[g]||(window[g]=dummy)});
(function(g,k,v,p){"undefined"==typeof nativendo_pc&&(nativendo_pc={});g.NativendoV2=function(p,q){var b=this;if("undefined"==typeof q){try{if(!p.endpoints||!p.identifier||!p.uniqueId)throw"Invalid configuration";}catch(a){console.log(a);return}b.endpoints=p.endpoints;b.identifier=p.identifier;b.uniqueId=p.uniqueId;b.options=p.options}try{if(b.currentUrl=g!==parent?top.location.href:location.href,!b.currentUrl)throw"location.href is undefined";}catch(a){b.currentUrl=k.referrer||location.href}b.gdpr=
1;b.gdprPd=null;b.gdprConsent="";"undefined"!=typeof g["nativendo_"+b.uniqueId+"_tcdata"]&&(b.gdpr=g["nativendo_"+b.uniqueId+"_tcdata"].gdpr,b.gdprPd=g["nativendo_"+b.uniqueId+"_tcdata"].gdprPd,b.gdprConsent=g["nativendo_"+b.uniqueId+"_tcdata"].gdprConsent);b.callback="function"==typeof p.callback?p.callback:function(){};b.trackMode="normal";b.hashRegex=/\-([a-z0-9]+)\.([a-z0-9]+)\.([a-z0-9]+)\.([a-z0-9]+)\.?(preview|heatmap|clickmap|lineup|survey\-[0-9]+|story\-[0-9]+)?\.?(0|1)?$/i;b.hashParts=[];
b.plugins={};b.duplicateCheck={};b.multipleUseCheck={};b.bidRequest={id:null,imp:[],site:{page:b.currentUrl,ref:k.referrer},tmax:2040};b.bidImp={id:null,tagid:null,secure:"https:"===k.location.protocol?1:0,"native":{context:1,contextsubtype:11,plcmttype:1,privacy:0,assets:[{id:1,required:1,title:{len:90}},{id:2,required:1,img:{wmin:300,hmin:300,type:3}},{id:4,required:1,data:{type:1,len:70}},{id:5,required:1,data:{type:2,len:350}}]},ext:{iframe:g!==parent,position:1}};b.dspRequestFormats={otto:{v:"v5.13.0-pre",
pageUrl:b.currentUrl,bidId:"",auctionId:"",transactionId:"",adUnitCode:"example-ad",params:{accountId:"seedingall",placementId:"exampleorg_Native",bidfloor:.1},sizes:[],mediaTypes:{"native":{image:{required:!0},title:{required:!0,len:40},clickUrl:{required:!0},body:{required:!0}}},gdprConsent:{consentString:"",consentRequired:!0}}};b.nodeRefresh={};b.waitUntilRefresh=3;b.refresh=function(a,c,d,e){var g=new b.DOM,u=Object.keys(b.stack),f=Math.round((new Date).getTime()/1E3);"undefined"==typeof d&&
(d=!0);"undefined"==typeof c&&(c=!0);"undefined"==typeof e&&(e=!0);a||(a=[]);Array.isArray(a)||(a=[a]);0==a.length&&(a=Object.keys(b.stack.nodes));a.forEach(function(a){if(!(b.nodeRefresh[a]&&f-b.waitUntilRefresh<b.nodeRefresh[a].t)){b.nodeRefresh[a]={t:f,c:b.nodeRefresh[a]?b.nodeRefresh[a].c+1:1};var m=[];u.forEach(function(c){switch(c){case "campaigns":break;case "htmlElements":b.stack[c][a]&&b.stack[c][a].forEach(function(a){m.push(a)});default:delete b.stack[c][a]}});e&&delete b.trackedInventory[a];
delete b.passbackInventory[a];b.findNodes(a,function(){m.forEach(function(a){g.destroy(a)})},c,d)}})};b.autorefresh=function(a,c,d){d*=1E3;var e=new b.Visibility,g=function(g,f){return e.isInViewport(a)&&e.isVisibleByStyle(a)?.5<=e.percentage(a)&&(d-=200,0>=d)?(f&&clearInterval(f),b.refresh(c),!0):!1:!1};setTimeout(function(){g()||e.every(200,function(a,b){g(a,b)})},200)};b.getEndpoint=function(a){return b.endpoints[a||"c"]||!1};b.getIdentifier=function(){return b.identifier};b.stack={nodes:{},targets:{},
campaigns:{},impIds:{},htmlElements:{},creatives:{}};b.setTrackMode=function(a){b.trackMode=a};b.setHashParts=function(a){b.hashParts=a};b.reco=!1;b.blocked=!1;b.trackedInventory={};b.passbackInventory={};b.initiated=!1;b.searchInterval=!1;b.findNodesAndRender=function(){if(b.initiated)return!1;var a=new b.DOM;b.initiated=!0;b.findNodes();b.searchInterval=setInterval(b.findNodes,40);a.ready(function(){b.searchInterval&&clearInterval(b.searchInterval);b.searchInterval=setInterval(b.findNodes,120);
setTimeout(function(){b.searchInterval&&clearInterval(b.searchInterval);var a=g["nativendo_"+b.uniqueId+"_map"];if("undefined"!=typeof a&&null!=a){var d=!1;Object.keys(a.d).forEach(function(b){a.d[b].used||("undefined"===typeof a.d[b].es||a.d[b].es?d=!0:a.d[b].ll||(a.d[b].found=!0,a.d[b].used=!0))});d&&(b.searchInterval=setInterval(b.findNodes,400))}},2040)});return!0};b.executedUserMatching=!1;b.renderQueue=[];b.renderData={};b.renderTimeoutId=null;b.xpathAdUnits={};b.findNodes=function(a,c,d,e){c=
"function"==typeof c?c:function(){};a=a?a:null;var m=new b.DOM,u=new b.Tracker,f=g["nativendo_"+b.uniqueId+"_map"],C=g["nativendo_"+b.uniqueId+"_conf"],n=0,t=0,r=0;if("undefined"!=typeof f&&null!=f){f.r&&(b.reco=!0);f.b&&(b.blocked=!0);try{Object.keys(f.d).forEach(function(c){a&&a!=c||f.d[c].x.forEach(function(a){b.xpathAdUnits[a]||(b.xpathAdUnits[a]={adUnitIds:[],adUnitId:null,renderedEventFired:!1});-1===b.xpathAdUnits[a].adUnitIds.indexOf(c)&&b.xpathAdUnits[a].adUnitIds.push(c)})}),Object.keys(f.d).forEach(function(h){n++;
f.d[h].found&&t++;f.d[h].used&&r++;a&&a!=h||(b.trackedInventory.hasOwnProperty(h)||"undefined"===typeof f.d[h].ti||f.d[h].ti||(b.trackedInventory[h]=h),f.d[h].x.forEach(function(a){var r=!0,n=!!f.d[h].or||e,w=null,t;-1!==a.indexOf("starts-with(")&&(t=m.findNode(a))&&t.id&&(a="#"+t.id);if(!n&&g.nativendo_pc.hasOwnProperty(a))r=!1,f.d[h].found=!0;else{if(w=m.findNode(a))f.d[h].found=!0;if(w===k.documentElement){g.nativendo_pc[a]=!0;return}}!1===d||b.trackedInventory.hasOwnProperty(h)||!w&&r||f.d[h].ll&&
!(new b.Visibility).isInViewport(w,C.lld)||(b.trackedInventory[h]=h,setTimeout(function(){u.trackEvent({aid:h},b.blocked?["data/inventory","data/blocked"]:"data/inventory",!1)},f.d[h].ll?0:400));if(r&&null!==w&&(!f.d[h].used||e)){var B=function(a,h,d,f,r){if(g.nativendo_pc[r]&&!n)return!1;if(h.ll){var m=new b.Visibility,k=C.lld;if(!m.isInViewport(d,k)){if("undefined"!==typeof b.checkOnMoveCallbacks&&b.checkOnMoveCallbacks[a])return!1;m.checkByMove(d,a,function(){return m.isInViewport(d,k)?(b.trackedInventory[a]||
"undefined"!==typeof f.d[a].ti&&!f.d[a].ti||(b.trackedInventory[a]=a,u.trackEvent({aid:a},b.blocked?["data/inventory","data/blocked"]:"data/inventory",!1)),f.d[a].ll=!1,B(a,f.d[a],d,f,r),!0):!1},u.passiveSupported,k);return!0}}if(("undefined"==typeof h.c.length||0<h.c.length||h.p)&&b.render({id:a,imp:h.id,rtb:h.rtb,bid:h.bid,campaigns:h.c,passback:h.p,target:d,nonce:f.n,xpath:r,group:h.g},e)&&(e=!1,c(),g.nativendo_pc[r]=!0,h.used=!0,h.ar))try{b.autorefresh(d,a,h.ar)}catch(K){}h.found&&!h.rendered&&
(h.rendered=!0);try{if(h.rendered&&!b.xpathAdUnits[r].renderedEventFired){var w=!0;b.xpathAdUnits[r].adUnitIds.some(function(a){var c=f.d[a];if(c.used)return b.xpathAdUnits[r].adUnitId=a,w=!0;c.rendered||(w=!1);return!1});if(w){var D=b.xpathAdUnits[r].adUnitId,t=D?f.d[D]:null,A=new CustomEvent("NativendoRendered",{detail:{adUnitIds:b.xpathAdUnits[r].adUnitIds,adUnitId:D,targetId:d.getAttribute("id"),target:d,xpath:r,filled:t&&t.used?!0:!1,passback:t&&t.used&&t.p&&("undefined"==typeof t.c.length||
0==t.c.length)?!0:!1}});b.xpathAdUnits[r].renderedEventFired=!0;g.dispatchEvent(A)}}}catch(K){console.debug(K)}return!0},q=[];if(f.dsp&&f.d[h].dsp){var p=function(c,d,e){var g=d=!1;try{if(c){var r=JSON.parse(c);switch(f.dsp[e].type){case "openrtb":r.seatbid&&r.seatbid.length&&r.seatbid[0].bid&&(r.bids=r.seatbid[0].bid);break;case "otto":var m=r[0];r={bids:[]};"undefined"!==typeof m&&(r.bids[0]={impid:m.requestId,price:m.cpm,ext:{creative:{id:m.creativeId}},adm:{"native":{assets:[{id:1,requred:1,title:{text:m.native.title}},
{id:2,required:1,img:m.native.image},{id:4,data:{value:"OTTO"}},{id:5,data:{type:2,value:m.native.body}}],link:{url:m.native.clickUrl,clicktrackers:m.native.clickTrackers},imptrackers:m.native.impressionTrackers}},adomain:["otto.de"]})}r&&0!==r.bids.length||(d=!0)}else d=!0}catch(N){d=!0}try{!b.executedUserMatching&&r.containerurl&&(b.executedUserMatching=!0,NativendoV2Loader.js(r.containerurl,!0,{"data-container-config":JSON.stringify(r.containerconfig)}))}catch(N){}var n="";if(!d){var k=function(a,
b,c,h){a=a/c*h;c=Math.abs(b-Math.ceil(a));return 3<Math.abs(b-Math.floor(a))||3<c?!1:!0};r.bids.forEach(function(c){if(f.d[h].id==c.impid){if("string"==typeof c.adm)try{c.adm=JSON.parse(c.adm)}catch(Q){return}if(c.adm&&(c.adm.native&&(c.adm=c.adm.native),!(c.ext&&c.ext.creative&&c.ext.creative.id&&-1!==Object.values(b.stack.creatives).indexOf(c.ext.creative.id)))){var d=null;c.ext&&c.ext.bidding_deal_id&&(d=c.ext.bidding_deal_id);if(!(null===d&&f.dsp&&f.dsp[e]&&f.dsp[e].deals_only||f.d[h].dsp[e]&&
f.d[h].dsp[e].at&&1==f.d[h].dsp[e].at.length&&(-1<f.d[h].dsp[e].at.indexOf("private_deals")&&!d||-1<f.d[h].dsp[e].at.indexOf("open_auction")&&d))){if(f.d[h].ir.s){var r;null!==d&&f.dsp&&f.dsp[e]&&f.dsp[e].deal&&f.dsp[e].deal[c.ext.bidding_deal_id]&&(r=f.dsp[e].deal[c.ext.bidding_deal_id]);if(r&&!r.ci){var m=!0;c.adm.assets.some(function(a){if(!a.img)return!1;var b=!1;(b=a.img.w&&a.img.h?k(a.img.w,a.img.h,f.d[h].ir.w,f.d[h].ir.h):r.sf.some(function(a){return k(f.d[h].ir.w,f.d[h].ir.h,a.w,a.h)}))||
(m=!1);return!0});if(!m)return}}"length"in f.d[h].c&&0===f.d[h].c.length&&(f.d[h].c={});f.d[h].rtb=!0;f.d[h].dspName=e;f.d[h].bid=c;f.d[h].c.rtb=[c.impid+".0"];f.d[h].p=!1;d=B(h,f.d[h],w,f,a);g=!0;d&&(c.nurl&&NativendoV2Loader.js(c.nurl),n=c.price)}}}})}if(d||!g)f.d[h].ll&&d&&(f.d[h].dsp=null,f.d[h].used=!1),B(h,f.d[h],w,f,a);return n};if(f.d[h].dsp){var v=!1;Object.keys(f.d[h].dsp).forEach(function(a,c){f.d[h].dsp[a].rsp||"1"!=f.d[h].dsp[a].s2s||((new b.Tracker).trackAuction({aid:h,floor:f.d[h].dsp[a]["p:enc"],
cpm:"",dsp:a}),delete f.d[h].dsp[a]);f.d[h].dsp[a]&&f.d[h].dsp[a].rsp&&!v&&(v=!0,f.d[h].used=!0,f.d[h].rtb=!1,c=p(f.d[h].dsp[a].rsp,200,a),(new b.Tracker).trackAuction({aid:h,floor:f.d[h].dsp[a]["p:enc"],cpm:c,dsp:a}))});if(v)return}Object.keys(f.dsp).forEach(function(a,c){if(f.d[h].dsp&&f.d[h].dsp[a]&&f.d[h].dsp[a].tid&&!f.d[h].dsp[a].rsp){C.gdpr&&(b.bidRequest.regs={ext:{gdpr:b.gdpr}},b.bidRequest.user={ext:{consent:b.gdprConsent}});c=JSON.parse(JSON.stringify(b.bidRequest));c.id=f.id+"-r"+(b.nodeRefresh[h]?
b.nodeRefresh[h].c:1)+"-s"+h;c.test=f.dsp[a].test;f.d[h].used=!0;f.d[h].rtb=!1;var d=JSON.parse(JSON.stringify(b.bidImp));d.id=f.d[h].id;d.tagid=f.d[h].dsp[a].tid;d.bidfloor=f.d[h].dsp[a]["p:enc"];d.native.plcmttype=f.d[h].ct;d.privacy=f.d[h].am?1:0;f.d[h].dsp[a]["p:raw"]&&(f.d[h].dsp[a].enc?d.bidfloor_raw=f.d[h].dsp[a]["p:raw"]:d.bidfloor=f.d[h].dsp[a]["p:raw"]);d.native.assets[1].img.wmin=f.d[h].ir.w;d.native.assets[1].img.hmin=f.d[h].ir.h;c.imp.push(d);switch(f.dsp[a].type){case "openrtb":d.native=
{request:d.native};break;case "otto":var e=b.dspRequestFormats[f.dsp[a].type];e.bidId=f.d[h].id;e.transactionId=f.id;e.auctionId=f.id;e.params.bidfloor=f.d[h].dsp[a]["p:raw"];e.params.placementId=f.d[h].dsp[a].tid;e.gdprConsent.consentRequired=!!c.regs.ext.gdpr;e.gdprConsent.consentString=c.user.ext.consent;d.native.assets.forEach(function(a){switch(!0){case "undefined"!==typeof a.title:e.mediaTypes.native.title.len=a.title.len;break;case a.data&&"undefined"!==typeof a.data.type&&2==a.data.type:e.mediaTypes.native.body.len=
a.data.len;break;case a.img&&"undefined"!==typeof a.img.type&&3==a.img.type:e.mediaTypes.native.image.sizes=[a.img.wmin,a.img.hmin]}});c=e}q.push(NativendoV2Loader.request("POST",f.dsp[a].endpoint.replace(/\[URL\]/g,(new b.URL).encode(b.currentUrl)),JSON.stringify(c),function(c,e){c=p(c,e,a);(new b.Tracker).trackAuction({aid:h,floor:d.bidfloor,cpm:c,dsp:a})},!0,2040,"application/json"))}});0<q.length&&Promise.all(q).then(function(){}).catch(function(a){})}0<q.length?setTimeout(function(){B(h,f.d[h],
w,f,a)},f.tmax):B(h,f.d[h],w,f,a)}}))})}catch(h){console.debug(h)}(t>=n||r>=n)&&b.searchInterval&&clearInterval(b.searchInterval)}};b.render=function(a,c){var d=new b.DOM,e=!1,m=g["nativendo_"+b.uniqueId+"_map"];Object.keys(a.campaigns).forEach(function(c){a.rtb&&"rtb"!=c||!a.rtb&&"rtb"==c||a.campaigns[c].forEach(function(c){if(!b.stack.nodes.hasOwnProperty(a.id)){c=c.split(".");if(m.mu&&-1<m.mu.indexOf(c[0])){b.multipleUseCheck[a.group]||(b.multipleUseCheck[a.group]=[]);if(-1<b.multipleUseCheck[a.group].indexOf(c[0]))return;
b.multipleUseCheck[a.group].push(c[0])}else if(b.stack.campaigns.hasOwnProperty(c[0]))return;if(a.group&&m.dc&&m.dc[c[0]]){b.duplicateCheck[a.group]||(b.duplicateCheck[a.group]=[]);for(var d=0,f=m.dc[c[0]].length;d<f;d++)if(-1===b.duplicateCheck[a.group].indexOf(m.dc[c[0]][d]))b.duplicateCheck[a.group].push(m.dc[c[0]][d]);else return}e=!0;b.stack.nodes[a.id]=a.nonce+"/"+a.id+"/"+c[0]+"/"+c[1]+"/"+(a.rtb?"1":"0");b.stack.targets[a.id]=a.target;b.stack.impIds[a.id]=a.imp;b.stack.campaigns[c[0]]={nodeId:a.id,
cti:c[1]};a.bid&&(a.bid.ext&&a.bid.ext.creative&&a.bid.ext.creative.id&&(b.stack.creatives[a.id]=a.bid.ext.creative.id),b.stack.nodes[a.id]+="/"+(a.bid.adm&&a.bid.adm.link&&-1<a.bid.adm.link.url.indexOf("rtb-adin")?"in":"out"));b.renderTeaser(b.stack.nodes[a.id]);b.nodeRefresh[a.id]={t:Math.round((new Date).getTime()/1E3),c:b.nodeRefresh[a.id]?b.nodeRefresh[a.id].c:0}}})});if(c&&!e)return Object.keys(b.stack.campaigns).forEach(function(c){a.id==b.stack.campaigns[c].nodeId&&delete b.stack.campaigns[c]}),
b.render(a,!1);b.passbackInventory.hasOwnProperty(a.id)||b.stack.nodes.hasOwnProperty(a.id)||!a.passback||(b.passbackInventory[a.id]=a.id,d.insertAndExecute(a.target,a.passback),e=!0);return e};b.renderTeaser=function(a){a=a.split("/").slice(1);b.renderQueue.push(a);a=a[0];var c=b.stack.targets[a]||null;if(c){var d={},e=/^data\-nativendo\-(.+)$/;Object.keys(c.attributes).forEach(function(a){a=c.attributes[a];var b=a.nodeName.match(e);b&&"undefined"!=typeof b[1]&&(d[b[1]]=a.nodeValue)});0<Object.keys(d).length&&
(b.renderData[a]=d)}b.renderTimeoutId||(b.renderTimeoutId=g.setTimeout(function(){var a=[],c=new g.nativendo[b.uniqueId].URL,d=g["nativendo_"+b.uniqueId+"_conf"],e=[];e.push("rid="+c.encode(g["nativendo_"+b.uniqueId+"_map"].id));e.push("url="+c.encode(g.nativendo[b.uniqueId].currentUrl));g!==parent&&e.push("if=1");d.gdpr&&(e.push("gdpr="+g.nativendo[b.uniqueId].gdpr),e.push("gdpr_pd="+g.nativendo[b.uniqueId].gdprPd),e.push("gdpr_consent="+g.nativendo[b.uniqueId].gdprConsent));for(c=function(a){var c=
[];a.forEach(function(d,e){var h=d[0],f=b.renderData[h]||{};Object.keys(f).forEach(function(a){c.push("data["+h+"]["+a+"]="+f[a])});a[e]=d.join(".")});var d=[e.join("&")];0<c.length&&d.push(c.join("&"));NativendoV2Loader.request("POST",b.getEndpoint("d")+"/cds/delivery/renders/"+a.join("-")+"/",d.join("&"),function(a,b){try{eval(a)}catch(A){}},!0,1E4)};0<b.renderQueue.length;)a.push(b.renderQueue.pop()),10<=a.length&&(c(a),a=[]);b.renderTimeoutId=null;0<a.length&&c(a)},16))};b.teaser=function(a,c){c=
"undefined"==typeof c?!0:c;var d=g["nativendo_"+b.uniqueId+"_map"];if(!c||b.stack.nodes.hasOwnProperty(a.id)){var e=function(d){var e=new b.DOM,h=new b.Observer;d=d||{};var f=g["nativendo_"+b.uniqueId+"_conf"],m=f.p;if(m.etr&&"object"==typeof m.etr)try{Object.keys(m.etr).forEach(function(b){a.etr||(a.etr={});a.etr[b]||(a.etr[b]=[]);m.etr[b].forEach(function(c){a.etr[b].push(c)})})}catch(E){console.debug(E)}var n=e.fromHTML(a.teaser),w=n.length;-1<["bottom","before","clear_inside"].indexOf(a.position)&&
(n=[].slice.call(n,0).reverse());for(var t=0,u=w-1;t<w;t++)(function(f){u--;1===f.nodeType&&("SCRIPT"===f.tagName?e.insertAndExecute(k.createElement("div"),f.outerHTML):(b.stack.htmlElements[a.id]=b.stack.htmlElements[a.id]||[],b.stack.htmlElements[a.id].push(f),e[a.position](f,c?b.stack.targets[a.id]:k.getElementById(a.target),"preview"==a.tm&&a.por),"clear_inside"===a.position&&(a.position="bottom"),"auto"==a.linking&&(f.style.cursor="pointer"),h.attach(a,f,d)))})(n[u]);-1<a.teaser.indexOf("nat-survey-ad")&&
("undefined"==typeof b.plugins["survey-ad"]?(b.plugins["survey-ad"]=null,NativendoV2Loader.js(b.endpoints.c+f.path.js+"plugins/survey-ad.js"+f.cq,!0,{"data-nati-plugin":"survey-ad"})):b.plugins["survey-ad"]&&b.plugins["survey-ad"].init());try{if(g!==F){var q=k.getElementsByTagName("img"),p=0,C=function(){try{var a=g["nativendo_"+b.uniqueId+"_conf"].p.pmp;a.height=k.getElementsByTagName("body")[0].scrollHeight;top.postMessage(JSON.stringify(a),"*")}catch(P){}},y=setInterval(function(){800<=p&&clearInterval(y);
C();++p},8);i=0;for(w=q.length;i<w;i++)q.onload=C;C()}}catch(E){console.debug(E)}if(b.stack.htmlElements[a.id]){a.css&&[].slice.call(e.fromHTML(a.css)).forEach(function(a){if(1===a.nodeType){if(-1<(" "+a.className+" ").replace(/[\n\t]/g," ").indexOf(" nativendo-render-hook ")){if(b.renderCssHookAdded)return;b.renderCssHookAdded=!0}e.bottom(a,v)}});a.js&&e.insertAndExecute(k.createElement("div"),a.js);try{if(a.truncate=!0,a.truncate){var F=b.stack.htmlElements[a.id][0].parentNode;-1!==["before","after"].indexOf(a.position)&&
(F=F.parentNode);var M=new b.Ellipsis;containers=[].slice.call(F.querySelectorAll(".nativendo-truncate-container"));images=[].slice.call(F.querySelectorAll("img"));containers.forEach(function(a){var b=a.querySelector(".nativendo-truncate-text");M.truncateOnLoad(a,b,images)})}}catch(E){console.debug(E)}try{Object.keys(a.plugins).forEach(function(c){a.plugins[c].forEach(function(d){if("js"==d)NativendoV2Loader[d](b.endpoints.c+f.path[d]+"plugins/"+c+"."+d+f.cq,!0,{"data-id":a.id+"."+a.lineItemId+"."+
a.lineItemCreativeId,"data-plugin":b.uniqueId+"."+c+"."+a.id});else NativendoV2Loader[d](b.endpoints.c+f.path[d]+"plugins/"+c+"."+d+f.cq)})})}catch(E){console.debug(E)}if(a.stc){var H=function(a,b,c){setTimeout(function(){var d=null;b.forEach(function(a){a.className=a.className.replace(/ nativendo-preview-highlight /,"",a.className);a=a.getBoundingClientRect();if(null===d||a.top<d)d=a.top});if(null!==d){var e=Math.round(d+a.pageYOffset-150);0>e&&(e=0);a.scrollTo(0,e);c&&setTimeout(function(){a.pageYOffset<=
e&&b.forEach(function(a){a.className+=" nativendo-preview-highlight "})},10)}},10)},I=!1;try{g.top!==g&&g.frameElement&&(I=!0,"scrollRestoration"in g.top.history&&"auto"==g.top.history.scrollRestoration&&g.top.addEventListener("pageshow",function(a){H(g.top,[g.frameElement],!0)}),H(g.top,[g.frameElement],!0))}catch(E){}"scrollRestoration"in g.history&&"auto"==g.history.scrollRestoration&&g.addEventListener("pageshow",function(c){H(g,b.stack.htmlElements[a.id],!I)});H(g,b.stack.htmlElements[a.id],
!I)}}};if(!1!==a.feed){var m=new b.Math,u=a.feed,f="nativendo_jsonp_callback"+m.uuidCompact().replace(/-/g,""),q="unknown";switch(!0){case -1!=u.indexOf("twiago"):q="twiago";break;case -1!=u.indexOf("plista"):q="plista";break;case -1!=u.indexOf("flashtalking"):q="flashtalking"}g[f]=function(c){var d={};try{if(c.assets)c.assets.forEach(function(a){a.title?d.title=a.title.text:a.link?d.url=a.link.url:a.data&&"2"==a.data.type?d.text=a.data.value:a.img&&"3"==a.img.type&&(d.img=a.img.url)}),c.eventtrackers&&
c.eventtrackers.forEach(function(b){"1"==b.method&&"1"==b.event&&(d.title=d.title+'<img src="'+b.url+'" style="position:absolute;visibility:hidden;width:1px;height:1px" />');"2"==b.method&&"1"==b.event&&(a.teaser=a.teaser+'<script src="'+b.url+'">\x3c/script>')});else if(c.creatives){var h={headline:"title",text:"text",image_4x3:"img",clickurl:"url",linktext:"readmore",url:"url"};for(f in h)d[h[f]]||"undefined"===typeof c.creatives[0][f]||(d[h[f]]=c.creatives[0][f]);for(h=0;1>=h;h++)if(d.title=d.title+
'<img src="'+c.creatives[h].viewtracking+'" style="position:absolute;visibility:hidden;width:1px;height:1px" />',c.creatives[h].pixels){var f=0;for(var g=c.creatives[h].pixels.length;f<g;f++)d.title=d.title+'<img src="'+c.creatives[h].pixels[f]+'" style="position:absolute;visibility:hidden;width:1px;height:1px" />'}}else d=c[0],"twiago"==q&&NativendoV2Loader.pixel(b.getEndpoint("t")+"/cds/track/log/?type=feed&msg=twiago-no-creatives")}catch(w){"twiago"==q&&NativendoV2Loader.pixel(b.getEndpoint("t")+
"/cds/track/log/?type=feed&msg=twiago-creatives-error");return}try{for(var m in d)d.hasOwnProperty(m)&&("img"==m&&-1==d[m].indexOf("?")&&(d[m]+="?"),a.teaser=a.teaser.replace(new RegExp("{"+m+"}","ig"),d[m]));a.url=d.url;e()}catch(w){}};var n=u.replace(/\{random\}|\[FT_RANDOM\]/g,m.uuidCompact()).replace(/\{url\}/g,encodeURIComponent(g.nativendo[b.uniqueId].currentUrl));"twiago"==q&&(n=n.replace(/\{gdpr\}/gi,g.nativendo[b.uniqueId].gdpr).replace(/\{gdpr_pd\}/gi,g.nativendo[b.uniqueId].gdprPd).replace(/\{gdpr_consent\}/gi,
g.nativendo[b.uniqueId].gdprConsent).replace(/(\?|\&)callback=\{callback\}/gi,""),NativendoV2Loader.request("GET",n,"",function(a,c){a&&"200"==c||NativendoV2Loader.pixel(b.getEndpoint("t")+"/cds/track/log/?type=feed&msg="+encodeURIComponent(JSON.stringify({s:c,u:n,r:a})));g[f](JSON.parse(a))},!0,5E3));q.match(/plista|flashtalking/)&&(n=n.replace(/\{callback\}/g,f),NativendoV2Loader.js(n))}else if(a.uca)try{d.d[a.id].id==a.impid&&function(){var c=d.d[a.id].bid,f=c.adm,h={title:"",text:"",img:"",readmore:"",
sponsored:"",url:f.link.url,privacy_icon:""};f.assets.forEach(function(c){if(c.title)h.title=c.title.text;else if(c.img){c={url:c.img.url,width:d.d[a.id].ir.w,height:d.d[a.id].ir.h,transform:"fit"};var e=/{img}([^"' ,]+)/i;if((e=a.teaser.match(e))&&e[1]){e=e[1].split("&");for(var f=[],g=0;g<e.length;g++)if(""!==e[g]){var m=e[g].split("=");c[m[0]]=m[1];"height"!==m[0]&&"width"!==m[0]||f.push(m[0])}e=/{img}([^"' ,]+)/ig;a.teaser=a.teaser.replace(e,"{img}");1===f.length&&(e=d.d[a.id].ir.w/d.d[a.id].ir.h,
"height"===f[0]?c.width=c.height*e:c.height=c.width/e)}switch(d.dsp[d.d[a.id].dspName].type){case "otto":c.mode="sc"}h.img=b.getEndpoint("c")+"/cdn/asset/image?"+(new b.URL).toQueryString(c)}else if(c.data)switch(c.id){case 4:case "4":h.sponsored=c.data.value;break;case 5:case "5":h.text=c.data.value}});f.privacy&&(h.privacy_icon='<a href="'+f.privacy+'" class="nativendo-oba-icon" target="_blank"><img src="'+b.getEndpoint("c")+'/cdn/asset/img/oba-icon.png"></a>');var m={bidid:c.id?c.id:"",cpm:c.price,
rtb:1,dsp:d.d[a.id].dspName,sponsored:h.sponsored,ext:c.ext?c.ext:""},n=Array.isArray(f.link.clicktrackers)?f.link.clicktrackers:[];if(-1<h.url.indexOf("rtb-adin")){if(!d.u||!d.u.match(/^https?:/))throw"No article url";var u=b.getEndpoint("d").replace(/^https?:\/\//,"").replace(/[-\/\\^$*+?.()|[\]{}]/g,"\\$&"),w=(u=(new RegExp("^(.*?)(https?(?:://|(?:[%A-F0-9])+2F)(?:"+u+")(?:/|(?:[%A-F0-9])+2F)(?:d|cds(?:/|(?:[%A-F0-9])+2F)delivery)(?:/|(?:[%A-F0-9])+2F)rtb-adin(?:/|(?:[%A-F0-9])+2F)(?:cid(?:/|(?:[%A-F0-9])+2F)|)([a-z0-9]+))",
"g")).exec(h.url))?!!u[1]:!1;if(!u)throw"no valid cid in bid.adm";var q=u[3],p=[b.uniqueId,a.id,q,"0"];a.url=d.u+"#/"+h.title.replace(/<\/?[^>]+(>|$)/g,"").replace(/[ .,!?]/g,"-").replace(/[^a-zA-Z0-9-_]/g,"").toLowerCase()+"-"+p.join(".");a.rtbcid=q;a.out=!1;w&&(0===h.url.indexOf("https://googleads.g.doubleclick.net/dbm/clk")?n.push('<iframe src="'+h.url+'" style="position:absolute;height:1px;width:1px;visibility:hidden;"></iframe>'):a.url=h.url.replace(u[2],encodeURIComponent(a.url)));h.url=a.url}else 0<
a.url.indexOf("{url}")?(h.url=g.encodeURIComponent(h.url)+"&"+(new b.URL).toQueryString(m),a.url=a.url.replace("{url}",h.url)):a.url=h.url;0<n.length&&(a.etr||(a.etr={click:[]}),n.forEach(function(b){0<b.indexOf("${AUCTION_PRICE}")&&(b=b.replace("${AUCTION_PRICE}",c.price));a.etr.click.push(b)}));Array.isArray(f.imptrackers)&&f.imptrackers.forEach(function(a){0<a.indexOf("${AUCTION_PRICE}")&&(a=a.replace("${AUCTION_PRICE}",c.price));h.title=h.title+'<img src="'+a+'" style="position:absolute;visibility:hidden;width:1px;height:1px" />'});
f.jstracker&&setTimeout(function(){(new b.DOM).insertAndExecute(k.createElement("div"),f.jstracker)},50);for(var C in h)h.hasOwnProperty(C)&&(a.teaser=a.teaser.replace(new RegExp("{"+C+"}","ig"),function(a){return this.replace}.bind({replace:h[C]})));e(m)}()}catch(t){console.debug(t)}else e()}};b.video=function(a){b.modal(a)};b.prospect=function(a){b.modal(a)};b.modal=function(a){var c=new b.DOM,d=new b.Tracker,e=new b.Visibility,m=c.fromHTML(a.html)[0],k=m.getElementsByClassName("nativendo-close")[0],
f=0,q=!0,n=g.top?g.top:g,p=n.document,r=n.document.getElementsByTagName("body")[0]||n.document.body,h=800;"max_modal_size"in g["nativendo_"+b.uniqueId+"_vars"]&&(h=g["nativendo_"+b.uniqueId+"_vars"].max_modal_size);"modal_css_hook"in g["nativendo_"+b.uniqueId+"_vars"]&&[].slice.call(c.fromHTML(g["nativendo_"+b.uniqueId+"_vars"].modal_css_hook)).forEach(function(a){1===a.nodeType&&c.bottom(a,m)});k.addEventListener("click",function(){c.destroy(m);q=!1},!1);b.modalSH=screen.availHeight;b.modalCoords=
null;c.bottom(m,r);var B=function(a,d){var e=a.getElementsByClassName("nativendo-content")[0];if(e&&(!d||b.modalSH!==screen.availHeight)){!e.getAttribute("data-style")&&e.setAttribute("data-style",e.getAttribute("style")?e.getAttribute("style"):"");!a.getAttribute("data-style")&&a.setAttribute("data-style",a.getAttribute("style")?a.getAttribute("style"):"");e.style.maxHeight="none";b.modalCoords||(a.style.width="auto",e.style.width||(e.style.width="auto"),b.modalCoords=c.getOffsetRect(e));a.style.display=
"none";var f=n.innerHeight&&(n.innerHeight-50<b.modalCoords.height||b.modalCoords.width>n.innerWidth);(" "+a.className+" ").match(/ nativendo\-(video|responsive)\-modal /g)&&(f=!1);if(f){var g=e.style,m=p.documentElement;a.style.position="absolute";g.position="absolute";g.top=(n.pageYOffset||p.scrollTop)-(p.clientTop||0)+"px";g.left=(n.pageXOffset||p.scrollLeft)-(p.clientLeft||0)+"px";g.width=(b.modalCoords.width<=n.innerWidth?n.innerWidth:b.modalCoords.width)+"px";g.marginBottom="0px";n.innerWidth>
h&&(g.width=h+"px",g.left=(""!=g.left?parseInt(g.left):0)+(n.innerWidth/2-h/2)+"px");a.style.width=Math.max(r.scrollWidth,r.offsetWidth,m.clientWidth,m.scrollWidth,m.offsetWidth)+"px";a.style.height=Math.max(r.scrollHeight,r.offsetHeight,m.clientHeight,m.scrollHeight,m.offsetHeight)+"px";b.modalCoords.width>parseInt(a.style.width)&&(g=g.left?parseInt(g.left):0,a.style.width=b.modalCoords.width+g+"px");d&&(b.modalSH=screen.availHeight)}f||(a.setAttribute("style",a.getAttribute("data-style")),e.setAttribute("style",
e.getAttribute("data-style")));a.style.display="block"}};b.modalResize||n.addEventListener("resize",function(){var a=p.getElementsByClassName("nativendo-modal")[0];a&&a.parentNode&&B(a,!0)},!0);b.modalResize=!0;B(m,!1);var A=m.getElementsByTagName("iframe");A.length&&e.every(100,function(a,b){for(a=0;a<A.length;a++)A[a]&&A[a].contentWindow||b&&clearInterval(b),e.isInViewport(A[a])&&e.isVisibleByStyle(A[a])&&1<=e.percentage(A[a])?A[a].contentWindow&&A[a].contentWindow.postMessage({nat_visible:!0},
"*"):A[a].contentWindow&&A[a].contentWindow.postMessage({nat_visible:!1},"*")});if("content"==a.type&&a.track_show_and_dwell){var D={noc:a.noc,aid:a.aid,cid:a.cid,cti:a.cti,sess:a.sess,ti:0};d.trackEvent(D,"content/show",!0);e.every(1E3,function(b,c){f=Math.round(b/1E3);if(!q||120<f)try{clearInterval(c)}catch(J){}else 0<f&&0===f%3&&(D.ti=f,d.trackEvent(D,a.type+"/dwell",!1))})}};b.getTargets=function(a,b,d){for(var c=!1,g={},u=0,f=b.length;u<f;u++){fixedLegacy=!1;try{for(var q=b[u].replace(/^.*(%.+?%).*$/,
"$1"),n=k.evaluate(b[u],k,null,XPathResult.ANY_TYPE,null),p=[];node=n.iterateNext();)p.push(node);p.forEach(function(b){switch(d[u]){case "nativendo-title":legacyContent=-1!==["TITLE","SCRIPT","STYLE"].indexOf(b.tagName)&&a.data.clean_title?a.data.clean_title:a.data.title;break;case "nativendo-article":legacyContent=a.data.article}b.innerHTML=b.innerHTML.replace(new RegExp(q,"ig"),legacyContent);fixedLegacy||-1!==["TITLE","SCRIPT","STYLE"].indexOf(b.tagName)||(b.id=d[u],fixedLegacy=!0)})}catch(h){}}try{for(var r in a.data)if(a.data[r])try{if(target=
k.getElementById("nativendo-"+r))c=!0,g[r]=target}catch(h){}}catch(h){return!1}return c?g:c};b.content=function(a,c,d){var e=new b.DOM,m=new b.Observer,u=new b.Visibility,f=new b.Tracker,q=g["nativendo_"+b.uniqueId+"_conf"],n,p=[],r=[];a.pre_js&&e.insertAndExecute(k.createElement("div"),a.pre_js);var h=b.getTargets(a,c,d);c.forEach(function(a){r.push(a.replace(/^.*(%.+?%).*$/,"$1"))});var B=function(c){function d(a,b){var c;a=[].slice.call(a.getElementsByClassName("nativendo-marker"));var d={};["noc",
"cid","aid","sess"].forEach(function(a){d[a]=b[a]});d.mid=[];a.forEach(function(a){var e={};["noc","cid","aid","sess"].forEach(function(a){e[a]=b[a]});try{if(c=JSON.parse(a.getAttribute("data-nativendo-custom-event")))if(e.mid=c.key,d.mid.push(c.key),"visibility"==c.type){var h=function(b,c){if(!u.isInViewport(a))return!1;c&&clearInterval(c);f.trackEvent(e,"marker/watch",!1);return!0};setTimeout(function(){h()||u.every(400,function(a,b){h(a,b)})},400)}}catch(I){}});0<d.mid.length&&f.trackEvent(d,
"marker/view")}if(!c)return!1;try{a.data.clean_title&&(k.title=a.data.clean_title)}catch(G){}for(var h in a.data)if(a.data[h]){try{if(n=c[h])switch(h){case "image":case "intro":n.innerHTML=a.data[h];p.push(n);break;case "title":var A=-1!==["TITLE","SCRIPT","STYLE"].indexOf(n.tagName)&&a.data.clean_title?a.data.clean_title:a.data.title;r.forEach(function(a){n.innerHTML=n.innerHTML.replace(new RegExp(a,"ig"),A)});-1===["TITLE","SCRIPT","STYLE"].indexOf(n.tagName)&&(n.innerHTML=A);break;case "article":var B=
a.data[h]+a.css;q.options.acs?e.insertAndExecute(n,B):n.innerHTML=B;a.js&&e.insertAndExecute(k.createElement("div"),a.js);p.push(n);b.adjustElements(n);try{d(n,a)}catch(G){}}}catch(G){console.debug(G)}"teasers"==h&&(b.reco=!1,a.data[h].forEach(function(a){try{b.teaser(a,!1)}catch(L){console.debug(L)}}))}Object.keys(a.plugins).forEach(function(c){a.plugins[c].forEach(function(a){NativendoV2Loader[a](b.endpoints.c+q.path[a]+"plugins/"+c+"."+a+q.cq)})});m.monitor(a,p);g.addEventListener("message",function(a){try{var b=
a.data.split(":");if("ifr"==b[0]&&"height"==b[1])for(var c=k.getElementsByTagName("iframe"),d=0;d<c.length;d++)if(c[d].contentWindow===a.source){c[d].height=b[2];break}}catch(F){}},!1);if("heatmap"==b.trackMode)try{setTimeout(function(){parent.postMessage('{"height": '+k.getElementsByTagName("body")[0].scrollHeight+"}",k.referrer)},1E3)}catch(G){console.debug(G)}};!1!==h?B(h):e.ready(function(){B(b.getTargets(a,c,d))})};b.adjustElements=function(a){var b,d,e;["img","video"].forEach(function(c){e=
a.getElementsByTagName(c);b=0;for(d=e.length;b<d;b++)if("img"!==c||""!=e[b].src)try{e[b].style.height="auto",e[b].style.width?(e[b].style.maxWidth=e[b].style.width,e[b].style.width="100%"):e[b].width&&(e[b].style.maxWidth=e[b].width+"px",e[b].style.width="100%")}catch(u){console.debug(u)}})};b.Date=function(){};b.Date.prototype={getTimestamp:function(){return Math.round((new Date).getTime()/1E3)}};b.NLP=function(){};b.NLP.prototype={getItemPropData:function(a){var b=["headline","alternativeHeadline",
"articleBody"],d={};z=0;for(li=b.length;z<li;z++){d[b[z]]=[];var e=a.querySelectorAll('*[itemprop="'+b[z]+'"]');i=0;for(l=e.length;i<l;i++)if(""!=e[i].innerText.replace(/[\n\s\t]/,"")&&void 0!=e[i].innerText&&"SCRIPT"!=e[i].tagName&&"STYLE"!=e[i].tagName&&"A"!=e[i].tagName)for(tmp=e[i].innerText.replace(/\n\n+/g,"\n").replace(/ [ ]+/g,"s").split("\n"),x=0,tl=tmp.length;x<tl;x++)tmp[x]=tmp[x].replace(/^\s+/g,"").replace(/\s+$/g,""),""!=tmp[x]&&d[b[z]].push(tmp[x])}return d},getBodyText:function(a){return(a.getElementsByTagName("body")[0]||
a.body).innerText.trim()},categorize:function(a,b,d){try{if(d=(new URL(d)).normalize(),!d)return!1}catch(e){return!1}NativendoV2Loader.request("POST",a+"/check-url",(new URLSearchParams({url:d})).toString(),function(c,m){200==m&&"1"==c&&(NativendoV2Nlp=g.NativendoV2Nlp||{url:d,processResults:function(c){c={url:d,website_id:b,text:c.articleText,meta_categories:c.metaCategories.join(","),meta_keywords:c.metaKeywords.join(",")};NativendoV2Loader.request("POST",a+"/add-url",(new URLSearchParams(c)).toString(),
function(a,b){},!0,5E3)}},NativendoV2Loader.js(p.endpoints.c+p.path.js+"nlp.js"+p.cq))},!0,5E3)}};b.DOM=function(){};b.DOM.prototype={getOffsetRect:function(a){a=a.getBoundingClientRect();var b=k.getElementsByTagName("body")[0],d=k.documentElement,e=b.getBoundingClientRect(),m=d.getBoundingClientRect(),q=g.pageYOffset||d.scrollTop||b.scrollTop,f=g.pageXOffset||d.scrollLeft||b.scrollLeft,p=d.clientTop||b.clientTop||0;d=d.clientLeft||b.clientLeft||0;var n=0,t=0;"getComputedStyle"in g&&"relative"==g.getComputedStyle(b).position&&
(n=e.top-m.top,t=e.left-m.left);return{top:Math.round(a.top+q-p-n),left:Math.round(a.left+f-d-t),width:a.width,height:a.height}},insertAndExecute:function(a,b){if(-1==b.indexOf("<"))try{Function('"use strict";'+b)()}catch(m){console.log("Passback failed with error: "+m)}else{a.innerHTML=b;for(var c=Array.prototype.slice.call(a.getElementsByTagName("script")),e=0;e<c.length;e++)if(""!=c[e].src)a=k.createElement("script"),""!=c[e].innerHTML&&(a.onload=function(){try{eval(c[e].innerHTML)}catch(m){}}),
a.src=c[e].src,k.getElementsByTagName("head")[0].appendChild(a);else try{eval(c[e].innerHTML)}catch(m){}}},ready:function(a){function b(){d||(d=!0,a())}var d=!1;try{var e=function(){return"complete"==k.readyState||"interactive"==k.readyState?(b(),!0):!1};if(!e()){if(k.onreadystatechange)var m=k.onreadystatechange;k.onreadystatechange=function(){e();try{m&&m()}catch(n){}}}}catch(n){}if(k.addEventListener)k.addEventListener("DOMContentLoaded",b,!1);else if(k.attachEvent){try{var q=null!=g.frameElement}catch(n){}if(k.documentElement.doScroll&&
!q){var f=function(){if(!d)try{k.documentElement.doScroll("left"),b()}catch(n){setTimeout(f,12)}};f()}k.attachEvent("onreadystatechange",function(){"complete"===k.readyState&&b()})}if(g.addEventListener)g.addEventListener("load",b,!1);else if(g.attachEvent)g.attachEvent("onload",b);else{var p=g.onload;g.onload=function(){p&&p();b()}}},fromHTML:function(a){var b=k.createElement("div");b.innerHTML=a;return b.childNodes},createElement:function(a,b){a=k.createElement(a);for(var c in b)if(b.hasOwnProperty(c))if("innerHTML"==
c||"innerText"==c)a[c]=b[c];else if("object"==typeof b[c])for(var e in b[c])b[c].hasOwnProperty(e)&&(a[c][e]=b[c][e]);else c.match(/on(load|error)/)?a[c]=b[c]:a.setAttribute(c,b[c]);return a},findNode:function(a){try{if(0<a.length&&"#"==a[0])return k.getElementById(a.substr(1));var b=k.evaluate(a,k,null,XPathResult.ANY_TYPE,null).iterateNext()}catch(d){return null}return b?b:null},before:function(a,b){var c=b.parentNode;c&&c.insertBefore(a,b);return a},after:function(a,b){var c=b.parentNode;c&&c.insertBefore(a,
b.nextSibling);return a},bottom:function(a,b,d){d&&(b.innerHTML="");b.appendChild(a);return a},clear_inside:function(a,b,d){return this.bottom(a,b,!0)},top:function(a,b,d){d&&(b.innerHTML="");b.insertBefore(a,b.firstChild);return a},inside:function(a,b){b.insertBefore(a,b.firstChild);return a},replace:function(a,b){a.parentNode.replaceChild(b,a);return b},destroy:function(a){return a.parentNode?(a.parentNode.removeChild(a),!0):a}};b.Event=function(a){this.params=a||{};this.set("ts",(new b.Date).getTimestamp())};
b.Event.prototype={set:function(a,b){this.params[a]=b},get:function(a){return this.params.hasOwnProperty(a)?this.params[a]:null},getAll:function(){return this.params}};b.Math=function(){this.chars="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".split("")};b.Math.prototype={uuidCompact:function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;return("x"==a?b:b&3|8).toString(16)})}};b.externalTracker=function(a){if(0===a.indexOf("<")){var c=
new b.DOM;[].slice.call(c.fromHTML(a)).forEach(function(a){"SCRIPT"===a.tagName?c.insertAndExecute(k.createElement("div"),a.outerHTML):c.bottom(a,k.getElementsByTagName("body")[0])})}else NativendoV2Loader.pixel(a)};b.Observer=function(){this.tra=new b.Tracker;this.vis=new b.Visibility;this.dom=new b.DOM;this.evOpt={};this.tra.passiveSupported&&(this.evOpt.passive=!0)};b.Observer.prototype={attach:function(a,c,d){var e=this,m=d||{},q=["noc","aid","cid","cti"],f=a.id;b.reco&&(m.reco=1,m.ocid=b.hashParts[3]);
"undefined"!==typeof a.target?q.forEach(function(b){m[b]=a[b]}):b.stack.nodes[f].split("/").forEach(function(a,b){q[b]&&(m[q[b]]=a)});b.stack.impIds[f]&&(m.imp=b.stack.impIds[f]);d.rtb&&(delete m.cid,a.rtbcid&&(m.cid=a.rtbcid));a.ll&&a.llit&&"visible"==a.llit||e.tra.trackEvent(m,"ad/view");var p=function(d,f){if(!e.vis.isInViewport(c)||!e.vis.isVisibleByStyle(c))return!1;if(.5<=e.vis.percentage(c)){f&&clearInterval(f);e.tra.trackEvent(m,a.ll&&a.llit&&"visible"==a.llit?["ad/view","ad/watch"]:"ad/watch");
try{if(a.etr&&"object"==typeof a.etr.watch){d=0;for(var h=a.etr.watch.length;d<h;d++)b.externalTracker(a.etr.watch[d]);a.etr.watch={}}}catch(A){}return!0}return!1};setTimeout(function(){p()||e.vis.every(400,function(a,b){p(a,b)})},400);if(c.getElementsByTagName("iframe").length){var n=c.getElementsByTagName("iframe")[0];e.vis.every(100,function(a,b){e.vis.isInViewport(n)&&e.vis.isVisibleByStyle(n)&&1<=e.vis.percentage(n)?n.contentWindow&&n.contentWindow.postMessage({nat_visible:!0},"*"):n.contentWindow&&
n.contentWindow.postMessage({nat_visible:!1},"*")})}if(a.modal&&g.top!==g&&0!==a.url.indexOf("#"))try{g.top.document}catch(r){a.modal=!1,newTab=!0,a.out=!0}var t=function(c){var d=this,f=1==c.button||c.ctrlKey||c.metaKey;if(!(1<c.button)){if(!d.href)return c.preventDefault(),!1;try{"undefined"==typeof a.etr&&(a.etr={click:[]});"[object String]"===Object.prototype.toString.call(a.etr.click)&&(a.etr.click=[a.etr.click]);d.hasAttribute("data-etr")&&(a.etr.click=[d.getAttribute("data-etr")]);for(var g=
0,r=a.etr.click.length;g<r;g++)b.externalTracker(a.etr.click[g])}catch(w){}if(d.hasAttribute("data-prop"))try{m.properties=JSON.parse(d.getAttribute("data-prop"))}catch(w){}e.tra.trackEvent(m,"ad/click",!1,function(){if(!(a.out||a.modal||f)){var b=a.url;d&&d.hasAttribute("data-href")&&(b=d.getAttribute("data-href"));""!=b&&setTimeout(function(){try{top.location.href?top.location.href=b:location.href=b}catch(O){location.href=b}},240)}});if(a.modal)return c.preventDefault(),0===k.getElementsByClassName("nativendo-modal").length&&
NativendoV2Loader.js(a.modal_url),!1;if(!a.out&&!f)return c.preventDefault(),!1}};a.ct&&"redirect"==a.ct&&(t=function(){});"auto"==a.linking?(d=function(b){var c=e.dom.getOffsetRect(b.target),d=function(a){a=a.target;"nativendo-dynamic-link"!=a.className&&(a=a.parentNode);a.parentNode.removeChild(a)};if(k.getElementById("vrm-quicknavigation")){b=e.dom.createElement("a",{"class":"nativendo-dynamic-link",href:a.url,innerHTML:"&nbsp;",target:a.out?"_blank":"_top",rel:"nofollow"});b.setAttribute("style",
"opacity:0.01;display:block;top:"+c.top+"px;left:"+c.left+"px;width:"+c.width+"px;height:"+c.height+"px;z-index:1400000;");try{b.style.setProperty("visibility","visible","important")}catch(D){}b.addEventListener("mouseout",d,!1);b.addEventListener("touchend",d,!1);e.dom.inside(b,k.getElementsByTagName("body")[0])}else{var f=e.dom.createElement("div",{"class":"nativendo-dynamic-link"});b=e.dom.createElement("a",{href:a.url,innerHTML:"&nbsp;",target:a.out?"_blank":"_top",rel:"nofollow"});f.style.top=
c.top+"px";f.style.left=c.left+"px";f.style.width=c.width+"px";f.style.height=c.height+"px";f.style.zIndex="1400000";try{f.style.setProperty("visibility","visible","important")}catch(D){}b.style.width=c.width+"px";b.style.height=c.height+"px";e.dom.inside(b,f);e.dom.inside(f,k.getElementsByTagName("body")[0]);f.addEventListener("mouseout",d,!1);f.addEventListener("touchend",d,!1)}b.addEventListener("click",t,!1);b.addEventListener("auxclick",t,!1)},c.addEventListener("mouseover",d,!1),c.addEventListener("touchstart",
d,this.evOpt)):(d=[].slice.call(c.querySelectorAll('a[href="'+a.url+'"]')),"A"===c.tagName&&c.getAttribute("href")===a.url&&d.push(c),d.forEach(function(b){b.setAttribute("target",a.out?"_blank":"_top");if(!b.getAttribute("rel")||-1==b.getAttribute("rel").indexOf("nofollow")){var c=b.getAttribute("rel");b.setAttribute("rel",(null!==c?c+" ":"")+"nofollow")}b.addEventListener("click",t,!1);b.addEventListener("auxclick",t,!1)}))},monitor:function(a,c){var d=this,e={noc:a.noc,aid:a.aid,cid:a.cid,cti:a.cti,
sess:a.sess,ti:0};"preview"!=b.trackMode&&g.addEventListener("hashchange",function(){var a=location.hash.match(b.hashRegex);if(a&&b.uniqueId==a[1]){if(0<b.hashParts.length){var c=!1;[2,3,4,6].forEach(function(d){b.hashParts[d]!=a[d]&&(c=!0)});"lineup"!=b.hashParts[5]&&"lineup"!=a[5]||b.hashParts[5]==a[5]||(c=!0);c&&(g.scrollTo(0,0),location.reload())}a[5]&&0===a[5].indexOf("story-")&&(a[5]=null);b.setTrackMode(a[5]?a[5]:"normal")}else location.hash&&(g.scrollTo(0,0),location.reload())});a.rtb&&(e.rtb=
1);if(a.track_show_and_dwell){d.tra.trackEvent(e,a.type+"/show",!0);var m=0;d.vis.every(1E3,function(b,c){m=Math.round(b/1E3);if(m>=a.rti)try{clearInterval(c)}catch(D){}else 0<m&&0===m%3&&(e.ti=m,d.tra.trackEvent(e,a.type+"/dwell",!1))},a.hiddenCallback);g.addEventListener("beforeunload",function(){e.ti=m;d.tra.trackEvent(e,a.type+"/dwell",!1)},!1);if("content"===a.type){var q={0:!1,25:!1,50:!1,75:!1,100:!1},f=1,p=0,n=function(){var b=k.getElementsByTagName("body")[0],c=k.documentElement,h=Math.max(b.scrollHeight,
b.offsetHeight,c.clientHeight,c.scrollHeight,c.offsetHeight),m=g.innerHeight||c.clientHeight;b=b.scrollTop||c.scrollTop;h=0<b?Math.round((b+m)/h*100):0;if(!(p>h||(p=h,h=95<=h?100:75<=h?75:50<=h?50:25<=h?25:0,q[h]))){q[h]=!0;0<h&&!q[h-25]&&(f=0);h={scr:h,dec:f};for(var n in e)h[n]=e[n];d.tra.trackEvent(h,a.type+"/scroll",!1)}};g.addEventListener("scroll",n,this.evOpt);n();var t=function(b){if(this.href){var c={u:this.href};for(f in e)c[f]=e[f];var f=a.type+"/clickout";-1!=this.className.indexOf("nativendo-image-link")&&
(f="image/click");try{b.which&&b.type&&"mousedown"==b.type?2==b.which&&d.tra.trackEvent(c,f,!1):d.tra.trackEvent(c,f,!1)}catch(w){}}};c.forEach(function(b){for(var c=b.getElementsByTagName("a"),f=0,h=c.length;f<h;f++)if(-1==c[f].className.indexOf("nativendo-social")&&("#"!=c[f].href.charAt(0)&&0!==c[f].href.indexOf("mailto:")&&(c[f].target="_blank"),!(c[f].hasAttribute("href")&&0==c[f].getAttribute("href").indexOf("#")||-1<c[f].href.replace(/^https?/,"").indexOf(a.article_url.replace(/^https?|\/$/g,
""))))){c[f].addEventListener("click",t,!1);try{c[f].addEventListener("dblclick",t,!1),c[f].addEventListener("mousedown",t,!1)}catch(J){}}c=b.getElementsByClassName("nativendo-image");var g=null;f=0;for(h=c.length;f<h;f++)c[f].addEventListener("load",function(){if("naturalWidth"in this&&1<this.naturalWidth)d.tra.trackEvent(e,"image/view",!1);else try{if(g=this.parentElement)"A"==g.nodeName&&"parentElement"in g&&(g=g.parentElement),g.parentElement.removeChild(g)}catch(J){}});b.addEventListener("click",
function(b){b={x:b.pageX,y:b.pageY,res:screen.availWidth+"x"+screen.availHeight};for(var c in e)b[c]=e[c];d.tra.trackEvent(b,a.type+"/click",!1)},!1)});c=k.getElementsByClassName("nativendo-social-link");n=["mail"];for(var r=0,h=c.length;r<h;r++)-1!==n.indexOf(c[r].getAttribute("data-rel"))&&c[r].addEventListener("click",function(){var a={u:this.href},b;for(b in e)a[b]=e[b];d.tra.trackEvent(a,"social/"+this.getAttribute("data-rel"),!1)},!1)}}}};b.Tracker=function(){var a=this;this.fired={};this.passiveSupported=
!1;try{var b=Object.defineProperty({},"passive",{get:function(){a.passiveSupported=!0}});g.addEventListener("test",null,b)}catch(d){}};b.Tracker.prototype={trackEvent:function(a,c,d,e){b.hashParts[6]&&0==c.indexOf("content/")&&(a.sa=1);if("normal"!=b.trackMode)return"function"==typeof e&&e(!1),!1;d="undefined"==typeof d?!0:d;var m=[],q=this,f=!1;"string"==typeof c?m.push(c):m=c;d&&m.forEach(function(a){if(q.fired.hasOwnProperty(a))return f||"function"!=typeof e||e(!1),f=!0,!1;q.fired[a]=!0});if(f)return!1;
try{if(b.options.tracking&&b.options.tracking.custom){var p,n=b.options.tracking.custom,t=g["nativendo_"+b.uniqueId+"_conf"].p;for(p in n)n.hasOwnProperty(p)&&t[n[p]]&&(a[p]=t[n[p]])}}catch(r){}a.t=c;try{a.aid&&b.nodeRefresh&&b.nodeRefresh[a.aid]&&(a.ar=b.nodeRefresh[a.aid].c)}catch(r){}try{if(a.url=g!==parent?top.location.href:location.href,!a.url)throw"location.href is undefined";}catch(r){a.url=k.referrer||location.href}this.log(new b.Event(a),e)},trackAuction:function(a){var b=["rtb/auction",
"rtb/request"];a.da=1;a.cpm&&b.push("rtb/response");this.trackEvent(a,b,!1)},log:function(a,c){new b.DOM;var d=(new b.Math).uuidCompact();try{g["nativendo_"+b.uniqueId+"_map"].id&&(d=g["nativendo_"+b.uniqueId+"_map"].id)}catch(e){}d=b.getEndpoint("t")+"/cds/tracking/event/"+d;a=(new b.URL).toQueryString(a.getAll());"function"!=typeof c&&(c=function(){});Promise.all([NativendoV2Loader.request("POST",d,a,function(a,b){},!0,3E4)]).then(function(){c(!0)}).catch(function(a){c(!1)})}};b.URL=function(){};
b.URL.prototype={encode:function(a){return encodeURIComponent(a).replace(/[!'()*]/g,function(a){return"%"+a.charCodeAt(0).toString(16)})},toQueryString:function(a,b){var c=[],e;for(e in a)if(a.hasOwnProperty(e)){var g=b?b+"["+e+"]":e,k=a[e];c.push("object"==typeof k?this.toQueryString(k,g):g+"="+this.encode(k))}return c.join("&")}};b.Visibility=function(){};b.Visibility.prototype={getHiddenProp:function(){if("hidden"in k)return"hidden";for(var a=["webkit","moz","ms","o"],b=0,d=a.length;b<d;b++)if(a[b]+
"Hidden"in k)return a[b]+"Hidden";return!1},isHidden:function(a){"undefined"==typeof a&&(a=this.getHiddenProp());return a?k[a]:!1},checkByMove:function(a,c,d,e,m){var k=g;if(g.top!==g)try{g.top.document,k=g.top}catch(f){}k===g&&g.IntersectionObserver?("undefined"===typeof b.checkOnMoveObserver&&(b.checkOnMoveObserver=new IntersectionObserver(function(a){a.forEach(function(a){a.isIntersecting&&"object"===typeof a.target.nativendoNodeUniqueKey&&a.target.nativendoNodeUniqueKey.forEach(function(c){b.checkOnMoveCallbacks[c]&&
b.checkOnMoveCallbacks[c]()&&(b.checkOnMoveObserver.unobserve(a.target),delete b.checkOnMoveCallbacks[c])})})},{rootMargin:m+"px"}),b.checkOnMoveCallbacks={}),"undefined"===typeof a.nativendoNodeUniqueKey&&(a.nativendoNodeUniqueKey=[]),a.nativendoNodeUniqueKey.push(c),b.checkOnMoveObserver.observe(a)):"undefined"===typeof b.checkOnMoveCallbacks&&(a=function(){k.clearTimeout(b.checkOnMoveId);b.checkOnMoveId=k.setTimeout(function(){Object.keys(b.checkOnMoveCallbacks).forEach(function(a){b.checkOnMoveCallbacks[a]()&&
delete b.checkOnMoveCallbacks[a]})},25)},k!==g.top?this.every(200,function(a,c){Object.keys(b.checkOnMoveCallbacks).forEach(function(a){b.checkOnMoveCallbacks[a]()&&delete b.checkOnMoveCallbacks[a]});0===Object.keys(b.checkOnMoveCallbacks).length&&(delete b.checkOnMoveCallbacks,g.clearInterval(c))}):(m={},e&&(m.passive=!0),k.addEventListener("scroll",a,m),k.addEventListener("resize",a,m),k.addEventListener("touchmove",a,m)),b.checkOnMoveCallbacks={});b.checkOnMoveCallbacks[c]=d},every:function(a,
b,d){var c=this,g=0;var k=setInterval(function(){c.isHidden()||"function"==typeof d&&d()||b(++g*a,k)},a)},on:function(a,b){var c=visibilityTracker.getHiddenProp();if(!c)return!1;g.onbeforeunload=function(){"leave"==a&&b()};k.addEventListener(c.replace(/[H|h]idden/,"")+"visibilitychange",function(){(visibilityTracker.isHidden()?"hidden":"visible")==a&&b()},!1);return!0},getCorrectElements:function(a){var b=g,d=k,e=!1;try{e=!!g.frameElement,g.frameElement&&top.document&&(a=g.frameElement,b=top.window,
d=top.document)}catch(m){}return{win:b,doc:d,el:a,isFrame:e}},isVisibleByStyle:function(a){if(!a||!a.parentNode)return!1;a=g.getComputedStyle(a,null).getPropertyValue("visibility");return"hidden"===a||"collapse"===a?!1:!0},isInViewport:function(a,b){var c=!1;if(!a)return!1;a=this.getCorrectElements(a);if(b&&!a.isFrame&&"none"==g.getComputedStyle(a.el).getPropertyValue("display")){var e=a.el.className;a.el.className+=" nativendo-visibility-check";c=!0}var m=a.el.getBoundingClientRect();if(!b&&(0>=
m.width||0>=m.height))return!1;b=b||0;b=0<m.right&&m.left<(a.win.innerWidth||a.doc.documentElement.clientWidth)&&m.top-b<(a.win.innerHeight||a.doc.documentElement.clientHeight)&&0<m.bottom+b;c&&(a.el.className=e);return b},percentage:function(a){if(!this.isInViewport(a)||!this.isVisibleByStyle(a))return 0;a=this.getCorrectElements(a);var b=a.el.getBoundingClientRect(),d=0,e=0;0<=b.top?d=Math.min(b.height,a.win.innerHeight-b.top):0<b.bottom&&(d=Math.min(a.win.innerHeight,b.bottom));0<=b.left?e=Math.min(b.width,
a.win.innerWidth-b.left):0<b.right&&(e=Math.min(a.win.innerWidth,b.right));return d*e/(b.height*b.width)}};b.Ellipsis=function(){var a=this;this.observer=new ResizeObserver(function(b,d){b.forEach(function(b){var c=b.target.__nativendoContent__;a.truncate(b.target.__nativendoContainer__,c,c.__nativendoBreakWord__)})})};b.Ellipsis.prototype={isTextOverflowing:function(a){var b={overflow:a.style.overflow,"overflow-y":a.style["overflow-y"],"max-height":a.style["max-height"],height:a.style.height};a.style.setProperty("overflow-y",
"visible","important");a.style.setProperty("max-height","none","important");a.style.setProperty("height","auto","important");var d=a.clientHeight;a.style.setProperty("overflow-y",b["overflow-y"]);a.style.setProperty("max-height",b["max-height"]);a.style.setProperty("height",b.height);a.style.setProperty("overflow","hidden","important");d=a.clientHeight<d;a.style.setProperty("overflow",b.overflow);return d},truncate:function(a,b,d){var c;if(a){b=b||a;b.__nativendoTruncateText__?b.innerText=b.__nativendoTruncateText__:
b.__nativendoTruncateText__=b.innerText;var g=b.innerText.length;d=d||!1;if(this.isTextOverflowing(a)){for(c=0;this.isTextOverflowing(a)&&0<g&&1E3>c;)c++,g--,b.innerText=b.innerText.substring(0,g);a=b.innerText;if(d)a=a.substring(0,a.length-4);else{d=g;c=0;do{c++;var k=a.lastIndexOf(" ",g-1);-1<k&&(a=a.substring(0,k),g=a.length)}while(-1<k&&k>d-4&&1E3>c)}0<a.length&&(a+=" ...");b.innerText=a}}},truncateOnLoad:function(a,b,d,e){var c=this;a&&(b=b||a,doc=a.ownerDocument,win=doc.defaultView||doc.parentWindow,
b.__nativendoBreakWord__=e,b.__nativendoContainer__=a,b.__nativendoContent__=b,win.addEventListener("load",function(){c.truncate(a,b,e)}),win.addEventListener("resize",function(){c.truncate(a,b,e)}),d.forEach(function(d){d.addEventListener("load",function(){c.truncate(a,b,e)});d.__nativendoObserveResize__||(d.__nativendoContainer__=a,d.__nativendoContent__=b,d.__nativendoObserveResize__=!0,c.observer.observe(d))}),b.__nativendoObserveResize__||(b.__nativendoObserveResize__=!0,c.observer.observe(b)),
a.__nativendoObserveResize__||(a.__nativendoContainer__=a,a.__nativendoContent__=b,a.__nativendoObserveResize__=!0,c.observer.observe(a)),c.truncate(a,b,e))}}}})(window,document,document.head||document.getElementsByTagName("head")[0],document.getElementsByTagName("body")[0]||document.body);
window.NativendoV2Loader=function(){function g(g){return function(k,p,y,q){p="undefined"==typeof p?!0:p;y="undefined"==typeof y?{}:y;q="undefined"===typeof q?document:q;return new Promise(function(b,a){setTimeout(function(){var c=q.createElement("pixel"==g?"img":g),d="body",e="src";c.onload=function(){b(k)};c.onerror=function(b){a(k+" / "+location.href)};c.onabort=function(b){a(k+" / "+location.href)};switch(g){case "script":c.async=p;preloadType="script";break;case "link":c.type="text/css";c.rel=
"stylesheet";preloadType="style";e="href";d="head";break;case "pixel":c.style="position:absolute;visibility:hidden;width:1px;height:1px;",preloadType="image"}c[e]=k;if(!navigator.userAgent.match(/(edge\/|mobile\/|android\/)/i))try{var m=q.createElement("link");m.href=k;m.rel="preload";m.as=preloadType;q.head.appendChild(m)}catch(u){}try{Object.keys(y).forEach(function(a){c.setAttribute(a,y[a])})}catch(u){}try{q[d]||"body"!=d||(d="head"),q[d].appendChild(c)}catch(u){a(k+"/ "+u+" / "+location.href)}},
0)})}}return{css:g("link"),js:g("script"),img:g("img"),pixel:g("pixel"),request:function(){return function(g,v,p,y,q,b,a){b="undefined"==typeof b?2500:b;a="undefined"==typeof a?"":a;return new Promise(function(c,d){var e=new XMLHttpRequest;e.open(g,v,"undefined"==typeof q?!0:q);e.withCredentials=!0;e.timeout=b;a||"post"!=g.toLowerCase()||(a="application/x-www-form-urlencoded");a&&e.setRequestHeader("Content-type",a);e.onreadystatechange=function(){e.readyState==XMLHttpRequest.DONE&&("function"==typeof y&&
y(e.responseText,e.status),c(v))};p?e.send(p):e.send()})}}()}}();
(function(g,k){g.nativendo=g.nativendo||{};for(var v=k.querySelectorAll("script[data-nativendo-instance]"),p=v.length,y=0;p>y;y++)(function(q){if(q&&"undefined"==typeof g.nativendo[q]){var b=g["nativendo_"+q+"_conf"];g.nativendo[q]=new NativendoV2(b);g["nativendo_"+q]=nativendo[q];if(b.external)b.data&&(new g.nativendo[q].Observer).monitor(b.data);else{b.dmp.forEach(function(a){if("undefined"==typeof a.endpoint)"undefined"==typeof g[a.type+"_segments"]&&(g[a.type+"_segments"]="");else{var c=g[a.type+
"_segments"]="";a.callback&&(c="nativendo_dmp_"+a.type,g[c]=function(b){try{switch(a.type){case "theadex":if("string"==typeof b&&(b=JSON.parse(b),b.data&&b.data.attributes&&b.data.attributes.segments&&b.data.attributes.segments.length)){b=b.data.attributes.segments;break}case "nativendo":b=b["segment-ids"]&&b["segment-ids"].length?b["segment-ids"]:!1;break;default:b=!1}b&&(g[a.type+"_segments"]||(g[a.type+"_segments"]=[]),g[a.type+"_segments"]=g[a.type+"_segments"].concat(b))}catch(B){console.debug(B)}});
var d="",e="",f="";b.gdpr&&(d=g.nativendo[q].gdpr,e=g.nativendo[q].gdprPd,f=g.nativendo[q].gdprConsent);0<a.endpoint.indexOf("{CALLBACK}")?NativendoV2Loader.js(a.endpoint.replace("{CALLBACK}",c).replace("${GDPR}",d).replace("${GDPR_PD}",e).replace(/\$\{GDPR_CONSENT(_\d+)?\}/g,f)):NativendoV2Loader.request("GET",a.endpoint.replace("${GDPR}",d).replace("${GDPR_PD}",e).replace(/\$\{GDPR_CONSENT(_\d+)?\}/g,f),!1,g[c])}});var a=[NativendoV2Loader.css(b.endpoints.c+b.path.css+"nativendo.css"+b.cq,!0,{id:"nativendo-css-link"})],
c=[];if(g.top!==g)try{g.top.document;if(g.top.document.getElementById("nativendo-css-link"))throw"css already available in top";a.push(NativendoV2Loader.css(b.endpoints.c+b.path.css+"nativendo.css"+b.cq,!0,{id:"nativendo-css-link"},g.top.document))}catch(f){}k.evaluate||a.push(NativendoV2Loader.js(b.endpoints.c+b.path.js+"wgx.js"+b.cq));var d=location.hash.match(g.nativendo[q].hashRegex),e=location.hash.match(/\/([a-z0-9]+)\/aid\/(\d+)\/cid\/(\d+)\/?(preview|heatmap|clickmap)?/i),m="";e&&e[1]==b.identifier&&
(d=["",q,0==e[2]?0:parseInt(e[2]+""<<8,10).toString(36),parseInt(e[3]+""<<8,10).toString(36),"0",e[4]]);d&&(d[1]==q?(m=d.slice(2,5).join("/"),c.push("reco=1"),d[5]&&"lineup"==d[5]||a.push(NativendoV2Loader.css(b.endpoints.c+b.path.css+"content.css"+b.cq))):d=!1);"undefined"!=typeof b.p.path&&(m=b.p.path);a.push(new Promise(function(a,d){try{-1<b.abc&&(0<b.abc&&(c.push("ab=1"),c.push("ig[]=500")),a());var e=k.createElement("DIV");e.id="sponsorText";e.style.position="absolute";e.style.left="-999px";
e.appendChild(k.createTextNode("&nbsp;"));var f=!1,g=0,h=setInterval(function(){if(!f){var b=k.getElementsByTagName("body")[0];if("undefined"==typeof b)return;b.appendChild(e);f=!0}++g;0==e.clientHeight&&(c.push("ab=1"),c.push("ig[]=500"));if(3<=g||0==e.clientHeight){clearInterval(h);try{k.getElementsByTagName("body")[0].removeChild(e)}catch(A){}a()}},16);setTimeout(function(){f||(c.push("ab=1"),c.push("ig[]=500"));h&&clearInterval(h);a()},1600)}catch(B){a()}}));var p=function(){var a=new g.nativendo[q].URL,
k=[];b.dmp.forEach(function(a){-1==k.indexOf(a.type)&&g[a.type+"_segments"]&&(k.push(a.type),c.push(a.type+"="+JSON.stringify(g[a.type+"_segments"])))});"undefined"!=typeof b.p&&"undefined"!=typeof b.p.url||c.push("url="+a.encode(g.nativendo[q].currentUrl));b.gdpr&&(c.push("gdpr="+g.nativendo[q].gdpr),c.push("gdpr_pd="+g.nativendo[q].gdprPd),c.push("gdpr_consent="+g.nativendo[q].gdprConsent));try{Object.keys(b.p).forEach(function(d){var e=b.p[d];e="object"===typeof e?JSON.stringify(e):a.encode(e);
c.push(d+"="+e)})}catch(r){}g!==parent&&c.push("if=1");var n;try{var p=top.document.querySelector('link[rel="canonical"]');p&&(n=p.getAttribute("href"))&&n!=g.nativendo[q].currentUrl&&c.push("canonical="+a.encode(n))}catch(r){}g["nativendo_"+q+"_conf"]&&g["nativendo_"+q+"_conf"].jobs&&g["nativendo_"+q+"_conf"].jobs.before_get&&g["nativendo_"+q+"_conf"].jobs.before_get.forEach(function(a,b){a()});Promise.all([NativendoV2Loader.request("POST",b.endpoints.d+"/cds/delivery/get/"+m,c.join("&"),function(a,
b){try{eval(a)}catch(B){}},!0,1E4)]).then(function(){try{NativendoNlpFeature&&b.endpoints.n&&g["nativendo_"+q+"_map"]&&g["nativendo_"+q+"_map"].w&&(new nativendo[q].NLP).categorize(b.endpoints.n,g["nativendo_"+q+"_map"].w,n&&n!=g.nativendo[q].currentUrl?n:g.nativendo[q].currentUrl);var c=d&&d[5]&&-1==["lineup"].indexOf(d[5])?d[5]:"normal",f=d&&d[5]&&"lineup"==d[5]?1:0,k=d&&d[2]&&"0"==d[2]||e?a.encode(g.nativendo[q].currentUrl):!1,p=c;c.match(/survey|story/)&&(c="normal");nativendo[q].setTrackMode(c);
if(d){nativendo[q].setHashParts(d);c=null;try{g["nativendo_"+q+"_map"].id&&(c=g["nativendo_"+q+"_map"].id)}catch(D){}NativendoV2Loader.js(b.endpoints.d+"/cds/delivery/content/"+m+"?tm="+p+(c?"&rid="+c:"")+(f?"&lu="+f:"")+(k?"&url="+k:"")+"&gdpr="+g.nativendo[q].gdpr+"&gdpr_pd="+g.nativendo[q].gdprPd+"&gdpr_consent="+g.nativendo[q].gdprConsent+"&m=0")}nativendo[q].findNodesAndRender()}catch(D){console.debug(D)}}).catch(function(a){})};Promise.all(a).then(function(){setTimeout(p,0<b.dmp.length?150:
0)}).catch(function(a){console.debug(a)})}}})(v[y].getAttribute("data-nativendo-instance"))})(window,document);
